### ISSUE TITLE
Formulario no bloquea registros erroneos

### ISSUE THREAD

**Issue by german-arq** [hnaranjo85/Backlog#13]
Al ejecutar el submit del formulario aunque los campos estén vacíos, incompletos o no cumplan con las políticas están pasando a la función agregarRegistro y por tanto al arreglo. Esto implica que si fuera una base de datos real se estarían guardando un montón de registros erróneos.

**Comment by hnaranjo85** [comment]
Hola compañeros... referente a la novedad que se está presentando a mi parecer no tiene que ver con la función de agregarRegistro del sprint3 sino que viene desde el sprint2. Aunque las funciones de validación de los campos detectan las expresiones regulares permitidas, en realidad no bloquean el envío del formulario en caso de no cumplirse. Si se toma el código validado por el boot para el sprint2 y sólo se modifica el archivo registro.html en el atributo action colocando por ejemplo que vaya a index.html notarán que aunque los campos presenten novedad igual se redirecciona al archivo o url indicada.
